[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aws_recommendations"
version = "0.0.8"
authors = [
  { name="dheeraj.banodha", email="dheerajmbanodha@gmail.com" },
]
description = "provides aws recommendations"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

#[project.urls]
#"Homepage" = ""
#"Bug Tracker" = ""