[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jasmin_mongo_configuration"
version = "0.0.4"
authors = [
  { name="BlackOrder", email="4302157+BlackOrder@users.noreply.github.com" },
]
description = "Links Jasmin SMS Gateway to MongoDB cluster stream (can be one node)."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [ "jasmin-telnet", "pymongo", "dnspython" ]

[project.scripts]
jasminmongoconfd = "jasmin_mongo_configuration.configurationstreamer:startFromConsole"

[project.urls]
"Homepage" = "https://github.com/BlackOrder/jasmin_mongo_configuration"
"Bug Tracker" = "https://github.com/BlackOrder/jasmin_mongo_configuration/issues"