[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "formsg-sdk"
version = "0.0.2"
authors = [
  { name="Shion Lee", email="shionlee92@gmail.com" },
]
description = "Python SDK for FormSG"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
