[project]
name = "fitterpp"
version = "0.0.8"
description = "Fitter parameters for an SBML model"
authors = [{ name = "Joseph Hellerstein", email = "joseph.hellerstein@gmail.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.6"

dependencies = [
    "jupyterlab",
    "lhsmdu",
    "lmfit",
    "matplotlib",
    "nose",
    "numpy",
    "pandas",
]

[project.urls]
Homepage = "https://github.com/ModelEngineering/fitterpp"

[options.package_data]
data = "*.txt, *.jpg, *.csv"

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
