[tool.poetry]
name = "anova-utils"
version = "0.3.2"
description = "Custom utility functions for conducting ANOVAs (or ANCOVAs)."
authors = ["Marcel Wiechmann <mail@mwiechmann.com>"]
license = "GNU GENERAL PUBLIC LICENSE v3"
readme = "README.md"
packages = [{include = "anova_utils"}]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^1.5.2"
scipy = "^1.9.3"
matplotlib = "^3.6.2"

[tool.poetry.group.optional]
optional = true

[tool.poetry.group.optional.dependencies]
statsmodels = "^0.13.5"
pingouin = "^0.5.2"
seaborn = "^0.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
