[build-system]
requires = ["setuptools > =61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "gcp_managed"
version = "0.0.0"
authors = [{name="prabhu", email="prabhupad@somwwhe.com"}]
description="App to produce and consume twitter json stream data"
readme="README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
