[tool.poetry]
name = "social_net_img_classifier"
version = "0.6.0"
description = ""
authors = ["Gabriel <gabriel@whaleandjaguar.co>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
boto3 = "^1.25.1"
bertopic = "0.12.0"
fuzzywuzzy = "0.18.0"
imblearn = "^0.0"
keras = "2.9.0"
langid = "1.1.6"
lightgbm = "3.3.2"
nltk = "3.7"
numpy = "1.21.3"
openai = "0.25.0"
optuna = "2.10.1"
pandas = "1.3.2"
Pillow = "9.1.1"
PyMySQL = "1.0.2"
python-Levenshtein = "0.20.5"
reverse_geocoder = "1.5.1"
scikit-learn = "1.1.1"
simpletransformers = "0.63.7"
six = "1.16.0"
spacy = "3.4.1"
transformers = "4.20.1"
torch = "1.10.1"
wj-social-net-queries = "^0.15.0"
requests = "^2.28.1"
tensorflow = "^2.1.0rc0"
onnxruntime = "1.12.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "library"
upload_to_pypi = true
upload_to_release = true
build_command = "poetry build"